name: Cypress Tests

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
          max-parallel: 4

        environment: testing

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"

            - name: create-json
              id: create-json
              uses: jsdaniell/create-json@1.1.2
              with:
                  name: "backend/malker-jam-firebase-adminsdk.json"
                  json: ${{ secrets.FIREBASE_CREDENTIALS }}

            - name: Set up .env
              run: |
                  echo ${{ secrets.ENV}} >> backend/.env

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.10.13

            - name: Install Backend Dependencies
              run: |
                  python -m pip install --upgrade pip
                  cd backend
                  pip install -r requirements.txt

            - name: Init backend
              run: |
                  cd backend
                  python app.py &

            - name: Wait for backend to be ready
              run: sleep 10

            - name: Install frontend dependencies
              run: npm install

            - name: Init frontend
              run: npm run dev &

            - name: Wait for frontend to be ready
              run: sleep 10

            - name: Run Cypress tests
              run: npm run cypress
